#!/bin/bash

secretname=744
name=noname
echo "Try to guess the secret name!"
echo
until [ "$name" = "$secretname" ]
do
read -p "Your guess: " name
done
sleep 1
echo "Congratulations! You found a flashlight that can be used throughout the dungeon."
