#!/bin/bash

cat <<EOF 

              Welcome to the dungeon of Corfu! We here at Corfu have a great community and offer great oppurtunities, 
              but to gain access you will need to pass the citizenship test. The test consists of gaining knowledge 
              about Corfu and problem solving. Hints will be at your disposal throughout the room. 
