#!/bin/bash

cat <<EOF 

              Welcome to the dungeon of Corfu! We here at Corfu have a great community and offer great oppurtunities, 
              but to gain access you will need to pass the citizenship test. 
