#!/bin/bash
#Environmental Variable:export MY_SHELL=$(cd ~Game)
MY_PWD=$(PWD:=cd START)
$PWD=MY_PWD

echo " "
echo "                  WELCOME TO OUR DUNGEON "
echo "		         GAME MENU "
echo " "
printf "			1.About game\n			2.Tutorial\n			3.Outcome\n			4.Start Game\n			5.Quit Game\n"

# use case switch to get input from the user

read -p "Enter your option: " choice
case "$choice" in

	1)
		printf "Welcome to our Dungeon. In this dungeon game you will navigate through our world using bash commands ls, cat, cd, and(sh or ./) commands.\nThere will be mini-challenges along your journey. Be careful and have fun exploring the Dungeon.\n "
		;;
	2)
		printf "cd – let’s you navigate through different rooms (For example: cd directoryName)\nls – shows you the list of files (for example: ls)\ncat – shows you the content of the file (For example: cat fileName)\nsh or ./  - let’s you run script (For example: ./scriptName or sh scriptName)\n"
		;;
	3)
		printf "The outcome for this game to successfully complete all tasks in all different rooms and gain knowledge on some basic commands of Linux.\n"
		;;
	4)	
		echo "$MY_PWD"
		;;
	5)
		exit 0
		;;
	*)
		echo "You entered an invalid option: $choice"		
esac





