#!/bin/bash

printf "\n\n"
printf "Once upon a time, there was a city located in the north side of Greece, called Saronida. Saronida was a beautiful city and full of nice and genuine people.\n\n"
sleep 1
printf "On the day of January 1 of 1895, a dreadful event took place and it left Saronida in ruins. Until this day, this event remain a mystery.\n\n"
sleep 1
printf "The event that took place on this horrifying day involved many high-ranking individuals in Saronida at the time and it resulted in an act of retaliation from another country well known as Turkey.\n\n"
sleep 1
printf "Ever since this incident took place, a lot of the building in the city are unrecognizable. Out of the building that was destroyed, one of the building remained intact and tourists would travel to Greece to visit that specific building.\n\n"
sleep 1
printf "In the span of 5 years, more than a few hundred-thousands of people visited this famous building.\n\n"
sleep 1
printf "Despite being this popular, no one was able to go inside of the building and get a closer because security would not allow it.\n\n"
sleep 1
printf "One day, one of the civilians claim they heard a voice screaming inside of the building and the civilian went near the building to investigate, but could not see anything.\n\n"
sleep 1
printf "Ever since then, the top executives in the city put out a flyer stating that whomever is brave enough to go inside the building to investigate this mysterious occurence will be rewarded.\n\n"
sleep 1
printf "The executives did not expect their proposition to actually work and now they have people from other countries coming to Greece to explore the building and in hope of collecting the reward.\n\n"
sleep 1
printf "This is how the famous maze known as The Isolated Maze was created. Now, more than a thousands guest every year go explore this maze."
