#!/bin/bash

import gold
export silver

gold=$gold
cat <<EOF

You will need as many weapons as you can afford.  The path will be dangerous so choose your weapons wisely.

The shopping list of weapons you can purchase

1.  Knife        1
2.  Sword        3
3.  net          1.25
4.  Poison Dart   .75

EOF




echo "You have $gold gold pieces to spend"
sleep 3
read -p "You can buy a weapon here.  Simply enter the # and it will add it to \
to your bag, when you do not have enough money left you will return to \
main room.     " weapon



if [[ "$gold" <= .5 ]]
	then	
		case $weapon in

			1) echo "you have purchased 1 knife"
			   sleep1
			   gold=$(($gold - 1))
			   echo "you have $gold gold pieces left"
			   echo "knife" >> weaponsBag
		    	;;
			
			2) echo "you have purchased 1 sword"
			   sleep 1
			   gold=$(($gold - 3))
			   echo "you have $gold gold pieces left"
			   echo "knife" >> weaponsBag
			;;
		esac
fi

	
   			   
echo "You cannot afford anymore weapons.   Good luck with the monsters"	
