#!/bin/bash
#Environmental Variables
# variable to set colors

TXT_Y=$(tput setaf 3)
TXT_R=$(tput sgr0)
echo " "
echo "Be careful with the decisions you make in this room"
echo " "
read -p "Do you still want to go ahead and explore the Zone area? [y,n]: " option
echo " "
sleep 1
case $option in
	y|Y)
		echo "You chose to continue. Now you can ${TXT_Y}cd Zone~${TXT_R}"
		;;
	n|N)
		echo "Since you wished not to continue, type ${TXT_Y}cd -1${TXT_R} in command prompt to relocate back to Room1."
		
		;;
esac

